os:
  - linux
  - osx
dist: xenial

compiler:
  - gcc
  - clang
  
sudo: required

cache:
  directories:
    - $HOME/Library/Caches/Homebrew
    - /usr/local/Homebrew

addons:
  apt:
    packages:
      - cpanminus
      - build-essential
      - libncurses5-dev
      - libpcre3-dev
      - libreadline-dev
      - libssl-dev
      - perl
      - etcd
      - luarocks
      - cmake
      - lua-check
  homebrew:
    update: true

before_cache:
  - brew cleanup

before_install:
  - ./utils/travis_runner.sh before_install

install:
  - ./utils/travis_runner.sh do_install

script:
  - ./utils/travis_runner.sh script

after_success:
  - ./utils/travis_runner.sh after_success